# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ac38e5c0bc27720b7706ef82355ce5d10e718aa531ddb5b356189a4acf8db8e5b171e65e6b3bd4a761c356509c67bf90118328d41a35efa3a8b54f36cf32cb3

test:
  secret_key_base: 0d6abf78b52900311038804d649bbf110fe8a117bf43278aae1d5e3dd6899dd4ce86659fb00b109195a30c96e3a1f84ba47bdfd5aaafe4bb3d0e74f1cb538f2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
